version: "3.1"

services:
  function:
    build: ./
    container_name: cruzhacks_hackers_applications_service
    env_file: .env
    ports:
      - "7071:80"
    depends_on:
      - database
  database:
    user: postgres
    image: postgres:11.3-alpine
    container_name: cruzhacks_hackers_applications_db
    volumes:
      - "./database/:/docker-entrypoint-initdb.d"
    restart: always
    # env_file: .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
      - "5430:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
